### ISSUE TITLE
manage plugin of the latest cpd-cli 11.0.0 is bad

### ISSUE THREAD

**Issue by robin2008** [IBM/cpd-cli#67]
1, download from below:
Just install cpd-cli v11.0.0 on x86_64 linux
[cpd-cli-linux-EE-11.0.0.tgz](https://github.com/IBM/cpd-cli/releases/download/v11.0.0/cpd-cli-linux-EE-11.0.0.tgz)

md5sum is f08f6c6bf627ebb9f2b8eb94195bef33

2, untar and just run
but failed to run `./cpd-cli manage`, output as below:
```
./cpd-cli manage
[INFO] 2022-07-07T23:37:23.111055Z Checking architecture: amd64
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
cpd-cli/plugins/cpd-cli manage/lib.GetSubCmdName(...)
	/root/cpd_cli_jenkins/workspace/cpd-cli-plugins-11.x.x/go/src/cpd-cli/plugins/cpd-cli manage/lib/lib.go:44
cpd-cli/plugins/cpd-cli manage/lib.RunSubCmd(0xc000133d30, 0x5c0c36)
	/root/cpd_cli_jenkins/workspace/cpd-cli-plugins-11.x.x/go/src/cpd-cli/plugins/cpd-cli manage/lib/lib.go:72 +0x3c5
cpd-cli/plugins/cpd-cli manage/cmd.glob..func1(0x7e0b80, 0xc000012210, 0x0, 0x0)
	/root/cpd_cli_jenkins/workspace/cpd-cli-plugins-11.x.x/go/src/cpd-cli/plugins/cpd-cli manage/cmd/root.go:49 +0x6c
github.com/spf13/cobra.(*Command).execute(0x7e0b80, 0xc000012210, 0x0, 0x0, 0x7e0b80, 0xc000012210)
	/root/cpd_cli_jenkins/workspace/cpd-cli-plugins-11.x.x/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x7e0b80, 0x0, 0x0, 0x0)
	/root/cpd_cli_jenkins/workspace/cpd-cli-plugins-11.x.x/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/root/cpd_cli_jenkins/workspace/cpd-cli-plugins-11.x.x/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
cpd-cli/plugins/cpd-cli manage/cmd.Execute()
	/root/cpd_cli_jenkins/workspace/cpd-cli-plugins-11.x.x/go/src/cpd-cli/plugins/cpd-cli manage/cmd/root.go:62 +0x2d
main.main()
	/root/cpd_cli_jenkins/workspace/cpd-cli-plugins-11.x.x/go/src/cpd-cli/plugins/cpd-cli manage/main.go:20 +0x25

[ERROR] 2022-07-07T23:37:23.114306Z Execution error:  exit status 2
```
Version:
```
./cpd-cli version
cpd-cli
	Version: 11.0
	Build Date: 2022-06-08T17:28:23
	Build Number: 20
	CPD Release Version: 4.5.0
```

```
file plugins/lib/linux/manage
plugins/lib/linux/manage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

# uname -a
Linux api.mayors.cp.fyre.ibm.com 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```

**Comment by robin2008** [comment]
it this only the error message not clear?
